"""Estados posibles de una Saga de orquestación."""

from enum import Enum


class SagaState(str, Enum):
    INICIADA = "INICIADA"
    PROVEEDOR_SELECCIONADO = "PROVEEDOR_SELECCIONADO"
    VERIFICACION_EN_PROCESO = "VERIFICACION_EN_PROCESO"
    VERIFICACION_PENDIENTE = "VERIFICACION_PENDIENTE"
    ESPERANDO_REINTENTO = "ESPERANDO_REINTENTO"
    PROVEEDOR_ACREDITADO = "PROVEEDOR_ACREDITADO"
    COTIZACION_EN_PROCESO = "COTIZACION_EN_PROCESO"
    COTIZACION_GENERADA = "COTIZACION_GENERADA"
    NOTIFICACION_EN_PROCESO = "NOTIFICACION_EN_PROCESO"
    COMPLETADA = "COMPLETADA"
    FALLIDA = "FALLIDA"
    COMPENSANDO = "COMPENSANDO"
    COMPENSADA = "COMPENSADA"
